#!/usr/bin/env python3
"""
Diagnostic script to analyze feature mismatch between ensemble models and current pipeline.
This will help us understand exactly what's going wrong with matchup intelligence integration.
"""

import os
import sys
import pandas as pd
import joblib
import numpy as np
from typing import Dict, List, Set

# Add project root to path
project_root = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, project_root)
sys.path.insert(0, os.path.join(project_root, 'src'))

def get_ensemble_model_features(position: str) -> Dict[str, any]:
    """Get expected features from ensemble model."""
    try:
        model_path = f'saved_models/{position}_ensemble_model.joblib'
        if not os.path.exists(model_path):
            return {'error': f'Model not found: {model_path}'}
        
        model = joblib.load(model_path)
        
        # Try different ways to access features
        result = {'position': position}
        
        # Try direct access
        if hasattr(model, 'feature_names_in_'):
            result['direct_features'] = list(model.feature_names_in_)
        
        # Try through rf_model
        if hasattr(model, 'rf_model') and hasattr(model.rf_model, 'model'):
            if hasattr(model.rf_model.model, 'feature_names_in_'):
                result['rf_features'] = list(model.rf_model.model.feature_names_in_)
        
        # Try through lgb_model  
        if hasattr(model, 'lgb_model') and hasattr(model.lgb_model, 'model'):
            if hasattr(model.lgb_model.model, 'feature_names_in_'):
                result['lgb_features'] = list(model.lgb_model.model.feature_names_in_)
        
        # Get model structure info
        result['model_type'] = type(model).__name__
        result['model_attributes'] = [attr for attr in dir(model) if not attr.startswith('_')]
        
        return result
        
    except Exception as e:
        return {'error': str(e), 'position': position}

def get_current_pipeline_features(position: str, include_matchup: bool = True) -> Dict[str, any]:
    """Get features generated by current pipeline."""
    try:
        from scripts.generate_draft_rankings import load_position_data
        
        print(f"Loading {position} data with matchup intelligence: {include_matchup}")
        df = load_position_data(position, include_matchup_intelligence=include_matchup)
        
        if df.empty:
            return {'error': f'No data loaded for {position}', 'position': position}
        
        # Get feature categories
        all_cols = set(df.columns)
        
        # Identify feature categories
        matchup_cols = [col for col in df.columns if any(x in col.lower() for x in ['next_', 'sos_', 'schedule', 'opponent'])]
        opportunity_cols = [col for col in df.columns if any(x in col.lower() for x in ['target_share', 'air_yards', 'wopr', 'adot'])]
        usage_cols = [col for col in df.columns if any(x in col.lower() for x in ['snap_share', 'route_participation', 'high_value', 'usage'])]
        basic_cols = [col for col in df.columns if any(x in col.lower() for x in ['carries', 'rushing_yards', 'receptions', 'receiving_yards', 'passing_yards'])]
        
        # Columns that would be dropped during feature preparation
        drop_cols = ['player_id', 'player_name', 'team', 'position', 'season', 
                     'fantasy_points', 'fantasy_points_per_game', 'current_team']
        feature_cols = [col for col in df.columns if col not in drop_cols]
        
        return {
            'position': position,
            'total_columns': len(df.columns),
            'feature_columns': len(feature_cols),
            'matchup_features': len(matchup_cols),
            'opportunity_features': len(opportunity_cols), 
            'usage_features': len(usage_cols),
            'basic_features': len(basic_cols),
            'sample_matchup': matchup_cols[:5],
            'sample_opportunity': opportunity_cols[:5],
            'sample_usage': usage_cols[:5],
            'sample_basic': basic_cols[:5],
            'all_feature_names': feature_cols,
            'players_loaded': len(df)
        }
        
    except Exception as e:
        return {'error': str(e), 'position': position}

def compare_features(model_features: List[str], pipeline_features: List[str]) -> Dict[str, any]:
    """Compare model expected features vs pipeline provided features."""
    model_set = set(model_features)
    pipeline_set = set(pipeline_features)
    
    missing = model_set - pipeline_set
    extra = pipeline_set - model_set
    matching = model_set & pipeline_set
    
    return {
        'model_expects': len(model_features),
        'pipeline_provides': len(pipeline_features),
        'matching': len(matching),
        'missing_in_pipeline': len(missing),
        'extra_in_pipeline': len(extra),
        'missing_features': sorted(list(missing))[:20],  # Show first 20
        'extra_features': sorted(list(extra))[:20],     # Show first 20
        'compatibility_score': len(matching) / len(model_set) if model_set else 0
    }

def main():
    """Run comprehensive feature analysis."""
    print("🔍 FEATURE MISMATCH DIAGNOSTIC ANALYSIS")
    print("=" * 60)
    
    positions = ['QB', 'RB', 'WR', 'TE']
    
    for position in positions:
        print(f"\n📊 ANALYZING {position} POSITION")
        print("-" * 40)
        
        # Get model features
        model_info = get_ensemble_model_features(position)
        if 'error' in model_info:
            print(f"❌ Model Error: {model_info['error']}")
            continue
            
        print(f"Model Type: {model_info.get('model_type', 'Unknown')}")
        
        # Get expected features (try RF first, then LGB)
        expected_features = None
        if 'rf_features' in model_info:
            expected_features = model_info['rf_features']
            print(f"✅ Found RF model features: {len(expected_features)}")
        elif 'lgb_features' in model_info:
            expected_features = model_info['lgb_features']
            print(f"✅ Found LGB model features: {len(expected_features)}")
        elif 'direct_features' in model_info:
            expected_features = model_info['direct_features']
            print(f"✅ Found direct features: {len(expected_features)}")
        else:
            print(f"❌ Could not extract expected features")
            print(f"Available attributes: {model_info.get('model_attributes', [])}")
            continue
        
        # Get current pipeline features with matchup intelligence
        pipeline_info = get_current_pipeline_features(position, include_matchup=True)
        if 'error' in pipeline_info:
            print(f"❌ Pipeline Error: {pipeline_info['error']}")
            continue
            
        print(f"Pipeline loaded: {pipeline_info['players_loaded']} players")
        print(f"Total features: {pipeline_info['feature_columns']}")
        print(f"Matchup features: {pipeline_info['matchup_features']}")
        print(f"Opportunity features: {pipeline_info['opportunity_features']}")
        
        # Compare features
        comparison = compare_features(expected_features, pipeline_info['all_feature_names'])
        
        print(f"\n🔄 COMPATIBILITY ANALYSIS:")
        print(f"   Model expects: {comparison['model_expects']} features")
        print(f"   Pipeline provides: {comparison['pipeline_provides']} features")
        print(f"   Matching: {comparison['matching']} features")
        print(f"   Missing: {comparison['missing_in_pipeline']} features")
        print(f"   Extra: {comparison['extra_in_pipeline']} features")
        print(f"   Compatibility: {comparison['compatibility_score']:.2%}")
        
        if comparison['missing_features']:
            print(f"\n❌ MISSING FEATURES (first 10):")
            for i, feature in enumerate(comparison['missing_features'][:10]):
                print(f"     {i+1:2d}. {feature}")
        
        if comparison['extra_features']:
            print(f"\n➕ EXTRA FEATURES (first 10):")
            for i, feature in enumerate(comparison['extra_features'][:10]):
                print(f"     {i+1:2d}. {feature}")
    
    print(f"\n✅ ANALYSIS COMPLETE")
    print("This analysis shows exactly why matchup intelligence fails!")

if __name__ == "__main__":
    main()