"""
RB Feature Engineering - Refactored Version

This module contains the RBFeatureEngineer class that inherits from BaseFeatureEngineer
and implements RB-specific feature engineering using centralized utilities.

This replaces the legacy rb_features.py with a cleaner, more maintainable architecture.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Union

from ..core.base_feature_engineer import BaseFeatureEngineer
from ..core.column_mapper import ColumnMapper
from ..core.feature_utils import FeatureCalculator


class RBFeatureEngineer(BaseFeatureEngineer):
    """
    Feature engineer for running back (RB) position.
    
    Inherits from BaseFeatureEngineer to provide standardized feature engineering
    with RB-specific calculations including efficiency metrics, usage patterns,
    opportunity metrics, and advanced analytics.
    """
    
    def __init__(self):
        """Initialize RB feature engineer with position-specific settings."""
        super().__init__(position='RB')
        self.column_mapper = ColumnMapper()
        self.feature_calculator = FeatureCalculator()
    
    def validate_data(self, df: pd.DataFrame) -> bool:
        """
        Validate that DataFrame contains required RB data.
        
        Args:
            df: DataFrame to validate
            
        Returns:
            bool: True if data is valid for RB feature engineering
        """
        if df.empty:
            self.logger.warning("Empty DataFrame provided for RB feature engineering")
            return False
            
        # Check for RB position data
        if 'position' not in df.columns:
            self.logger.error("Missing 'position' column in DataFrame")
            return False
            
        rb_data = df[df['position'] == 'RB']
        if rb_data.empty:
            self.logger.warning("No RB data found in DataFrame")
            return False
            
        # Check for at least one rushing or receiving stat column
        rushing_cols = self.column_mapper.get_column_mapping(df, ['rushing'])
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        has_rushing_stats = any(rushing_cols.values())
        has_receiving_stats = any(receiving_cols.values())
        
        if not has_rushing_stats and not has_receiving_stats:
            self.logger.warning("No rushing or receiving statistics columns found for RB feature engineering")
            
        return True
    
    def get_required_columns(self) -> List[str]:
        """
        Get list of columns required for RB feature engineering.
        
        Returns:
            List of column names that must be present in input data
        """
        return [
            'position',  # Required to filter to RB data
            'games'  # Required for per-game calculations
        ]
    
    def get_generated_features(self) -> List[str]:
        """
        Get list of features that will be generated by this engineer.
        
        Returns:
            List of feature names that will be added to the DataFrame
        """
        return [
            # Basic efficiency metrics
            'yards_per_carry',
            'yards_per_reception',
            'yards_per_touch',
            'touchdowns_per_touch',
            'catch_rate',
            
            # Per-game metrics
            'rushing_yards_per_game',
            'rushing_tds_per_game',
            'carries_per_game',
            'receiving_yards_per_game',
            'receiving_tds_per_game',
            'receptions_per_game',
            'targets_per_game',
            'touches_per_game',
            'total_yards_per_game',
            'total_tds_per_game',
            
            # Usage and opportunity metrics
            'target_share',
            'red_zone_carries',
            'red_zone_targets',
            'red_zone_touches',
            'goal_line_carries',
            'snap_share',
            'touch_share',
            'opportunity_share',
            
            # Advanced efficiency metrics
            'yards_after_contact_per_carry',
            'broken_tackles_per_touch',
            'receiving_air_yards_share',
            'receiving_target_quality',
            'rush_success_rate',
            'receiving_success_rate',
            
            # Role classification features
            'workhorse_score',
            'committee_back_score',
            'pass_catching_back_score',
            'goal_line_back_score',
            'rb_versatility_score',
            
            # Consistency and volatility metrics
            'rb_efficiency_consistency',
            'weekly_touch_volatility',
            'boom_game_rate',
            'bust_game_rate'
        ]
    
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate RB-specific features from player data.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with RB-specific features added
        """
        if not self.validate_data(df):
            return df.copy()
        
        # Filter to RB data only
        df_rb = df[df['position'] == 'RB'].copy()
        
        if df_rb.empty:
            return df_rb
        
        self.logger.info(f"Engineering features for {len(df_rb)} RB records")
        
        try:
            # Calculate basic efficiency metrics
            df_rb = self._calculate_efficiency_metrics(df_rb)
            
            # Calculate per-game averages
            df_rb = self._calculate_per_game_metrics(df_rb)
            
            # Calculate usage and opportunity metrics
            df_rb = self._calculate_usage_metrics(df_rb)
            
            # Calculate advanced metrics
            df_rb = self._calculate_advanced_metrics(df_rb)
            
            # Calculate role classification features
            df_rb = self._calculate_role_classification(df_rb)
            
            self.logger.info("RB feature engineering completed successfully")
            return df_rb
            
        except Exception as e:
            self.logger.error(f"Error in RB feature engineering: {str(e)}")
            raise
    
    def _calculate_efficiency_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate RB efficiency metrics using centralized column mapping.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with RB efficiency metrics added
        """
        df = df.copy()
        
        # Get standardized column mappings
        rushing_cols = self.column_mapper.get_column_mapping(df, ['rushing'])
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Yards per carry
        carries_col = rushing_cols.get('rushing_attempts')
        rushing_yards_col = rushing_cols.get('rushing_yards')
        
        if carries_col and rushing_yards_col:
            df['yards_per_carry'] = np.where(
                df[carries_col] > 0,
                df[rushing_yards_col] / df[carries_col],
                0.0
            )
        else:
            df['yards_per_carry'] = 0.0
        
        # Yards per reception
        receptions_col = receiving_cols.get('receptions')
        receiving_yards_col = receiving_cols.get('receiving_yards')
        
        if receptions_col and receiving_yards_col:
            df['yards_per_reception'] = np.where(
                df[receptions_col] > 0,
                df[receiving_yards_col] / df[receptions_col],
                0.0
            )
        else:
            df['yards_per_reception'] = 0.0
        
        # Calculate total touches and yards
        touches = 0
        total_yards = 0
        
        if carries_col and carries_col in df.columns:
            touches += df[carries_col]
        if receptions_col and receptions_col in df.columns:
            touches += df[receptions_col]
            
        if rushing_yards_col and rushing_yards_col in df.columns:
            total_yards += df[rushing_yards_col]
        if receiving_yards_col and receiving_yards_col in df.columns:
            total_yards += df[receiving_yards_col]
        
        # Yards per touch
        df['yards_per_touch'] = np.where(touches > 0, total_yards / touches, 0.0)
        
        # Touchdowns per touch
        total_tds = 0
        rushing_tds_col = rushing_cols.get('rushing_touchdowns')
        receiving_tds_col = receiving_cols.get('receiving_touchdowns')
        
        if rushing_tds_col and rushing_tds_col in df.columns:
            total_tds += df[rushing_tds_col]
        if receiving_tds_col and receiving_tds_col in df.columns:
            total_tds += df[receiving_tds_col]
            
        df['touchdowns_per_touch'] = np.where(touches > 0, total_tds / touches, 0.0)
        
        # Catch rate
        targets_col = receiving_cols.get('targets')
        if targets_col and receptions_col and targets_col in df.columns and receptions_col in df.columns:
            df['catch_rate'] = np.where(
                df[targets_col] > 0,
                df[receptions_col] / df[targets_col],
                0.0
            )
        else:
            df['catch_rate'] = 0.0
        
        return df
    
    def _calculate_per_game_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate RB per-game metrics using centralized utilities.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with RB per-game metrics added
        """
        df = df.copy()
        
        # Get games played column
        general_cols = self.column_mapper.get_column_mapping(df, ['general'])
        games_col = general_cols.get('games')
        if not games_col:
            self.logger.warning("No games column found for per-game calculations")
            # Set all per-game metrics to 0
            per_game_metrics = [
                'rushing_yards_per_game', 'rushing_tds_per_game', 'carries_per_game',
                'receiving_yards_per_game', 'receiving_tds_per_game', 'receptions_per_game',
                'targets_per_game', 'touches_per_game', 'total_yards_per_game', 'total_tds_per_game'
            ]
            for metric in per_game_metrics:
                df[metric] = 0.0
            return df
        
        # Get column mappings
        rushing_cols = self.column_mapper.get_column_mapping(df, ['rushing'])
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Avoid division by zero
        games_played = df[games_col].replace(0, 1)
        
        # Rushing per-game stats
        rushing_stats = {
            'rushing_yards_per_game': rushing_cols.get('rushing_yards'),
            'rushing_tds_per_game': rushing_cols.get('rushing_touchdowns'),
            'carries_per_game': rushing_cols.get('rushing_attempts')
        }
        
        for stat_name, col_name in rushing_stats.items():
            if col_name and col_name in df.columns:
                df[stat_name] = df[col_name] / games_played
            else:
                df[stat_name] = 0.0
        
        # Receiving per-game stats
        receiving_stats = {
            'receiving_yards_per_game': receiving_cols.get('receiving_yards'),
            'receiving_tds_per_game': receiving_cols.get('receiving_touchdowns'),
            'receptions_per_game': receiving_cols.get('receptions'),
            'targets_per_game': receiving_cols.get('targets')
        }
        
        for stat_name, col_name in receiving_stats.items():
            if col_name and col_name in df.columns:
                df[stat_name] = df[col_name] / games_played
            else:
                df[stat_name] = 0.0
        
        # Combined per-game stats
        df['touches_per_game'] = df['carries_per_game'] + df['receptions_per_game']
        df['total_yards_per_game'] = df['rushing_yards_per_game'] + df['receiving_yards_per_game']
        df['total_tds_per_game'] = df['rushing_tds_per_game'] + df['receiving_tds_per_game']
        
        return df
    
    def _calculate_usage_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate RB usage and opportunity metrics.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with RB usage metrics added
        """
        df = df.copy()
        
        # For now, set basic usage metrics to 0 or calculate from available data
        # In a full implementation, these would require team-level data
        
        # Target share (would need team passing attempts)
        df['target_share'] = 0.0
        
        # Red zone and goal line opportunities (would need play-by-play data)
        df['red_zone_carries'] = 0.0
        df['red_zone_targets'] = 0.0
        df['red_zone_touches'] = 0.0
        df['goal_line_carries'] = 0.0
        
        # Snap share (would need snap count data)
        df['snap_share'] = 0.0
        
        # Touch and opportunity shares (would need team totals)
        df['touch_share'] = 0.0
        df['opportunity_share'] = 0.0
        
        return df
    
    def _calculate_advanced_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate advanced RB metrics and analytics.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with advanced RB metrics added
        """
        df = df.copy()
        
        # Advanced metrics that would require more detailed data
        # For now, set to 0 or estimate from available stats
        
        df['yards_after_contact_per_carry'] = 0.0
        df['broken_tackles_per_touch'] = 0.0
        df['receiving_air_yards_share'] = 0.0
        df['receiving_target_quality'] = 0.0
        df['rush_success_rate'] = 0.0
        df['receiving_success_rate'] = 0.0
        
        return df
    
    def _calculate_role_classification(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate RB role classification scores based on usage patterns.
        
        Args:
            df: DataFrame containing RB player data
            
        Returns:
            DataFrame with role classification features added
        """
        df = df.copy()
        
        # Workhorse score (based on carry volume and consistency)
        df['workhorse_score'] = np.where(
            df['carries_per_game'] >= 15,
            df['carries_per_game'] / 20.0,  # Scale to 0-1
            0.0
        )
        
        # Committee back score (inverse of workhorse)
        df['committee_back_score'] = np.where(
            df['carries_per_game'] < 12,
            1.0 - (df['carries_per_game'] / 12.0),
            0.0
        )
        
        # Pass-catching back score (based on targets and receptions)
        df['pass_catching_back_score'] = np.where(
            df['targets_per_game'] >= 3,
            df['targets_per_game'] / 8.0,  # Scale to 0-1
            0.0
        )
        
        # Goal line back score (would be based on goal line carries if available)
        df['goal_line_back_score'] = 0.0
        
        # Versatility score (combination of rushing and receiving)
        rush_component = np.minimum(df['carries_per_game'] / 15.0, 1.0)
        receiving_component = np.minimum(df['targets_per_game'] / 5.0, 1.0)
        df['rb_versatility_score'] = (rush_component + receiving_component) / 2.0
        
        # Consistency metrics (would need game-by-game data)
        df['rb_efficiency_consistency'] = 0.0
        df['weekly_touch_volatility'] = 0.0
        df['boom_game_rate'] = 0.0
        df['bust_game_rate'] = 0.0
        
        return df


# Legacy compatibility function
def engineer_rb_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Legacy compatibility function for RB feature engineering.
    
    This function maintains backward compatibility with existing code
    while using the new RBFeatureEngineer class internally.
    
    Args:
        df: DataFrame containing RB player data
        
    Returns:
        DataFrame with RB-specific features added
    """
    engineer = RBFeatureEngineer()
    return engineer.engineer_features(df)