"""
TE Feature Engineering - Refactored Version

This module contains the TEFeatureEngineer class that inherits from BaseFeatureEngineer
and implements TE-specific feature engineering using centralized utilities.

This replaces the legacy te_features.py with a cleaner, more maintainable architecture.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Union

from ..core.base_feature_engineer import BaseFeatureEngineer
from ..core.column_mapper import ColumnMapper
from ..core.feature_utils import FeatureCalculator


class TEFeatureEngineer(BaseFeatureEngineer):
    """
    Feature engineer for tight end (TE) position.
    
    Inherits from BaseFeatureEngineer to provide standardized feature engineering
    with TE-specific calculations including efficiency metrics, target analytics,
    blocking vs receiving role classification, and red zone usage.
    """
    
    def __init__(self):
        """Initialize TE feature engineer with position-specific settings."""
        super().__init__(position='TE')
        self.column_mapper = ColumnMapper()
        self.feature_calculator = FeatureCalculator()
    
    def validate_data(self, df: pd.DataFrame) -> bool:
        """
        Validate that DataFrame contains required TE data.
        
        Args:
            df: DataFrame to validate
            
        Returns:
            bool: True if data is valid for TE feature engineering
        """
        if df.empty:
            self.logger.warning("Empty DataFrame provided for TE feature engineering")
            return False
            
        # Check for TE position data
        if 'position' not in df.columns:
            self.logger.error("Missing 'position' column in DataFrame")
            return False
            
        te_data = df[df['position'] == 'TE']
        if te_data.empty:
            self.logger.warning("No TE data found in DataFrame")
            return False
            
        # Check for at least one receiving stat column
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        if not any(receiving_cols.values()):
            self.logger.warning("No receiving statistics columns found for TE feature engineering")
            
        return True
    
    def get_required_columns(self) -> List[str]:
        """
        Get list of columns required for TE feature engineering.
        
        Returns:
            List of column names that must be present in input data
        """
        return [
            'position',  # Required to filter to TE data
            'games'  # Required for per-game calculations
        ]
    
    def get_generated_features(self) -> List[str]:
        """
        Get list of features that will be generated by this engineer.
        
        Returns:
            List of feature names that will be added to the DataFrame
        """
        return [
            # Basic efficiency metrics
            'catch_rate',
            'yards_per_reception',
            'yards_per_target',
            'touchdowns_per_reception',
            'touchdowns_per_target',
            'target_quality',
            
            # Per-game metrics
            'targets_per_game',
            'receptions_per_game',
            'receiving_yards_per_game',
            'receiving_tds_per_game',
            
            # TE-specific usage metrics
            'target_share',
            'red_zone_targets',
            'red_zone_receptions',
            'red_zone_touchdowns',
            'goal_line_targets',
            'snap_share',
            'route_participation_rate',
            
            # Advanced receiving metrics
            'yards_after_catch_per_reception',
            'average_depth_of_target',
            'contested_catch_rate',
            'seam_route_rate',
            'slot_alignment_rate',
            'inline_alignment_rate',
            
            # Role classification features
            'receiving_specialist_score',
            'blocking_specialist_score',
            'hybrid_te_score',
            'red_zone_specialist_score',
            'matchup_dependent_score',
            'elite_tier_score',
            
            # Consistency and reliability metrics
            'target_consistency_score',
            'weekly_production_volatility',
            'reliable_target_rate',
            'te_versatility_score',
            'blocking_snap_estimate'
        ]
    
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate TE-specific features from player data.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with TE-specific features added
        """
        if not self.validate_data(df):
            return df.copy()
        
        # Filter to TE data only
        df_te = df[df['position'] == 'TE'].copy()
        
        if df_te.empty:
            return df_te
        
        self.logger.info(f"Engineering features for {len(df_te)} TE records")
        
        try:
            # Calculate basic efficiency metrics
            df_te = self._calculate_efficiency_metrics(df_te)
            
            # Calculate per-game averages
            df_te = self._calculate_per_game_metrics(df_te)
            
            # Calculate usage and opportunity metrics
            df_te = self._calculate_usage_metrics(df_te)
            
            # Calculate advanced metrics
            df_te = self._calculate_advanced_metrics(df_te)
            
            # Calculate role classification features
            df_te = self._calculate_role_classification(df_te)
            
            self.logger.info("TE feature engineering completed successfully")
            return df_te
            
        except Exception as e:
            self.logger.error(f"Error in TE feature engineering: {str(e)}")
            raise
    
    def _calculate_efficiency_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate TE efficiency metrics using centralized column mapping.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with TE efficiency metrics added
        """
        df = df.copy()
        
        # Get standardized column mappings
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Extract key columns
        targets_col = receiving_cols.get('targets')
        receptions_col = receiving_cols.get('receptions')
        receiving_yards_col = receiving_cols.get('receiving_yards')
        receiving_tds_col = receiving_cols.get('receiving_touchdowns')
        
        # Catch rate (receptions / targets)
        if targets_col and receptions_col and both_cols_exist(df, [targets_col, receptions_col]):
            df['catch_rate'] = np.where(
                df[targets_col] > 0,
                df[receptions_col] / df[targets_col],
                0.0
            )
        else:
            df['catch_rate'] = 0.0
        
        # Yards per reception
        if receptions_col and receiving_yards_col and both_cols_exist(df, [receptions_col, receiving_yards_col]):
            df['yards_per_reception'] = np.where(
                df[receptions_col] > 0,
                df[receiving_yards_col] / df[receptions_col],
                0.0
            )
        else:
            df['yards_per_reception'] = 0.0
        
        # Yards per target
        if targets_col and receiving_yards_col and both_cols_exist(df, [targets_col, receiving_yards_col]):
            df['yards_per_target'] = np.where(
                df[targets_col] > 0,
                df[receiving_yards_col] / df[targets_col],
                0.0
            )
        else:
            df['yards_per_target'] = 0.0
        
        # Touchdowns per reception
        if receptions_col and receiving_tds_col and both_cols_exist(df, [receptions_col, receiving_tds_col]):
            df['touchdowns_per_reception'] = np.where(
                df[receptions_col] > 0,
                df[receiving_tds_col] / df[receptions_col],
                0.0
            )
        else:
            df['touchdowns_per_reception'] = 0.0
        
        # Touchdowns per target
        if targets_col and receiving_tds_col and both_cols_exist(df, [targets_col, receiving_tds_col]):
            df['touchdowns_per_target'] = np.where(
                df[targets_col] > 0,
                df[receiving_tds_col] / df[targets_col],
                0.0
            )
        else:
            df['touchdowns_per_target'] = 0.0
        
        # Target quality (combination of yards per target and TD rate)
        df['target_quality'] = (df['yards_per_target'] * 0.7) + (df['touchdowns_per_target'] * 30.0)
        
        return df
    
    def _calculate_per_game_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate TE per-game metrics using centralized utilities.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with TE per-game metrics added
        """
        df = df.copy()
        
        # Get games played column
        general_cols = self.column_mapper.get_column_mapping(df, ['general'])
        games_col = general_cols.get('games')
        if not games_col:
            self.logger.warning("No games column found for per-game calculations")
            # Set all per-game metrics to 0
            per_game_metrics = [
                'targets_per_game', 'receptions_per_game', 
                'receiving_yards_per_game', 'receiving_tds_per_game'
            ]
            for metric in per_game_metrics:
                df[metric] = 0.0
            return df
        
        # Get column mappings
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Avoid division by zero
        games_played = df[games_col].replace(0, 1)
        
        # Receiving per-game stats
        receiving_stats = {
            'targets_per_game': receiving_cols.get('targets'),
            'receptions_per_game': receiving_cols.get('receptions'),
            'receiving_yards_per_game': receiving_cols.get('receiving_yards'),
            'receiving_tds_per_game': receiving_cols.get('receiving_touchdowns')
        }
        
        for stat_name, col_name in receiving_stats.items():
            if col_name and col_name in df.columns:
                df[stat_name] = df[col_name] / games_played
            else:
                df[stat_name] = 0.0
        
        return df
    
    def _calculate_usage_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate TE usage and opportunity metrics.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with TE usage metrics added
        """
        df = df.copy()
        
        # For now, set basic usage metrics to 0 or calculate from available data
        # In a full implementation, these would require team-level and play-by-play data
        
        # Target share (would need team passing attempts)
        df['target_share'] = 0.0
        
        # Red zone and goal line opportunities (would need play-by-play data)
        df['red_zone_targets'] = 0.0
        df['red_zone_receptions'] = 0.0
        df['red_zone_touchdowns'] = 0.0
        df['goal_line_targets'] = 0.0
        
        # Snap share and route participation (would need snap count data)
        df['snap_share'] = 0.0
        df['route_participation_rate'] = 0.0
        
        return df
    
    def _calculate_advanced_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate advanced TE metrics and analytics.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with advanced TE metrics added
        """
        df = df.copy()
        
        # Advanced metrics that would require more detailed data
        # For now, set to 0 or estimate from available stats
        
        df['yards_after_catch_per_reception'] = 0.0
        df['average_depth_of_target'] = 0.0
        df['contested_catch_rate'] = 0.0
        df['seam_route_rate'] = 0.0
        df['slot_alignment_rate'] = 0.0
        df['inline_alignment_rate'] = 0.0
        
        return df
    
    def _calculate_role_classification(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate TE role classification scores based on usage patterns.
        
        Args:
            df: DataFrame containing TE player data
            
        Returns:
            DataFrame with role classification features added
        """
        df = df.copy()
        
        # Receiving specialist score (based on target volume and efficiency)
        df['receiving_specialist_score'] = np.where(
            df['targets_per_game'] >= 5,
            (df['targets_per_game'] / 8.0) * (df['catch_rate'] + 0.3),  # Weighted by targets and catch rate
            0.0
        )
        
        # Blocking specialist score (inverse of receiving - would be based on blocking snaps if available)
        df['blocking_specialist_score'] = np.where(
            df['targets_per_game'] < 3,
            1.0 - (df['targets_per_game'] / 5.0),
            0.0
        )
        
        # Hybrid TE score (balanced receiving and blocking)
        df['hybrid_te_score'] = np.where(
            (df['targets_per_game'] >= 3) & (df['targets_per_game'] <= 6),
            0.8 - abs(df['targets_per_game'] - 4.5) / 3.0,  # Peak at 4.5 targets/game
            0.0
        )
        
        # Red zone specialist score (would be based on red zone targets if available)
        df['red_zone_specialist_score'] = np.minimum(df['touchdowns_per_target'] * 10.0, 1.0)
        
        # Matchup dependent score (low target consistency - would need game-by-game data)
        df['matchup_dependent_score'] = 0.0
        
        # Elite tier score (based on overall production)
        df['elite_tier_score'] = np.where(
            (df['targets_per_game'] >= 6) & (df['yards_per_target'] >= 8),
            (df['targets_per_game'] / 10.0 + df['yards_per_target'] / 12.0) / 2.0,
            0.0
        )
        
        # Consistency metrics (would need game-by-game data)
        df['target_consistency_score'] = 0.0
        df['weekly_production_volatility'] = 0.0
        df['reliable_target_rate'] = 0.0
        
        # Versatility score (combination of different role scores)
        df['te_versatility_score'] = (
            df['receiving_specialist_score'] * 0.4 +
            df['hybrid_te_score'] * 0.3 +
            df['red_zone_specialist_score'] * 0.3
        )
        
        # Blocking snap estimate (inverse of receiving usage)
        df['blocking_snap_estimate'] = np.maximum(0.3, 1.0 - (df['targets_per_game'] / 10.0))
        
        return df


def both_cols_exist(df: pd.DataFrame, columns: List[str]) -> bool:
    """Helper function to check if all columns exist in DataFrame."""
    return all(col in df.columns for col in columns if col is not None)


# Legacy compatibility function
def engineer_te_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Legacy compatibility function for TE feature engineering.
    
    This function maintains backward compatibility with existing code
    while using the new TEFeatureEngineer class internally.
    
    Args:
        df: DataFrame containing TE player data
        
    Returns:
        DataFrame with TE-specific features added
    """
    engineer = TEFeatureEngineer()
    return engineer.engineer_features(df)