"""
WR Feature Engineering - Refactored Version

This module contains the WRFeatureEngineer class that inherits from BaseFeatureEngineer
and implements WR-specific feature engineering using centralized utilities.

This replaces the legacy wr_features.py with a cleaner, more maintainable architecture.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Optional, Union

from ..core.base_feature_engineer import BaseFeatureEngineer
from ..core.column_mapper import ColumnMapper
from ..core.feature_utils import FeatureCalculator


class WRFeatureEngineer(BaseFeatureEngineer):
    """
    Feature engineer for wide receiver (WR) position.
    
    Inherits from BaseFeatureEngineer to provide standardized feature engineering
    with WR-specific calculations including efficiency metrics, target analytics,
    opportunity metrics, and advanced route-running features.
    """
    
    def __init__(self):
        """Initialize WR feature engineer with position-specific settings."""
        super().__init__(position='WR')
        self.column_mapper = ColumnMapper()
        self.feature_calculator = FeatureCalculator()
    
    def validate_data(self, df: pd.DataFrame) -> bool:
        """
        Validate that DataFrame contains required WR data.
        
        Args:
            df: DataFrame to validate
            
        Returns:
            bool: True if data is valid for WR feature engineering
        """
        if df.empty:
            self.logger.warning("Empty DataFrame provided for WR feature engineering")
            return False
            
        # Check for WR position data
        if 'position' not in df.columns:
            self.logger.error("Missing 'position' column in DataFrame")
            return False
            
        wr_data = df[df['position'] == 'WR']
        if wr_data.empty:
            self.logger.warning("No WR data found in DataFrame")
            return False
            
        # Check for at least one receiving stat column
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        if not any(receiving_cols.values()):
            self.logger.warning("No receiving statistics columns found for WR feature engineering")
            
        return True
    
    def get_required_columns(self) -> List[str]:
        """
        Get list of columns required for WR feature engineering.
        
        Returns:
            List of column names that must be present in input data
        """
        return [
            'position',  # Required to filter to WR data
            'games'  # Required for per-game calculations
        ]
    
    def get_generated_features(self) -> List[str]:
        """
        Get list of features that will be generated by this engineer.
        
        Returns:
            List of feature names that will be added to the DataFrame
        """
        return [
            # Basic efficiency metrics
            'catch_rate',
            'yards_per_reception',
            'yards_per_target',
            'touchdowns_per_reception',
            'touchdowns_per_target',
            'target_quality',
            
            # Per-game metrics
            'targets_per_game',
            'receptions_per_game',
            'receiving_yards_per_game',
            'receiving_tds_per_game',
            
            # Usage and opportunity metrics
            'target_share',
            'air_yards_share',
            'red_zone_targets',
            'red_zone_receptions',
            'deep_targets',
            'slot_usage_rate',
            'snap_share',
            
            # Advanced receiving metrics
            'average_depth_of_target',
            'yards_after_catch_per_reception',
            'air_yards_per_target',
            'contested_catch_rate',
            'separation_at_catch',
            'route_diversity_score',
            
            # Target analytics
            'high_value_target_rate',
            'short_target_rate',
            'medium_target_rate',
            'deep_target_rate',
            'intermediate_accuracy',
            'deep_accuracy',
            
            # Role classification features
            'primary_receiver_score',
            'slot_receiver_score',
            'deep_threat_score',
            'possession_receiver_score',
            'red_zone_specialist_score',
            
            # Consistency and reliability metrics
            'target_consistency_score',
            'weekly_production_volatility',
            'boom_game_rate',
            'reliable_target_rate',
            'wr_versatility_score'
        ]
    
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Generate WR-specific features from player data.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with WR-specific features added
        """
        if not self.validate_data(df):
            return df.copy()
        
        # Filter to WR data only
        df_wr = df[df['position'] == 'WR'].copy()
        
        if df_wr.empty:
            return df_wr
        
        self.logger.info(f"Engineering features for {len(df_wr)} WR records")
        
        try:
            # Calculate basic efficiency metrics
            df_wr = self._calculate_efficiency_metrics(df_wr)
            
            # Calculate per-game averages
            df_wr = self._calculate_per_game_metrics(df_wr)
            
            # Calculate usage and opportunity metrics
            df_wr = self._calculate_usage_metrics(df_wr)
            
            # Calculate advanced metrics
            df_wr = self._calculate_advanced_metrics(df_wr)
            
            # Calculate role classification features
            df_wr = self._calculate_role_classification(df_wr)
            
            self.logger.info("WR feature engineering completed successfully")
            return df_wr
            
        except Exception as e:
            self.logger.error(f"Error in WR feature engineering: {str(e)}")
            raise
    
    def _calculate_efficiency_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate WR efficiency metrics using centralized column mapping.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with WR efficiency metrics added
        """
        df = df.copy()
        
        # Get standardized column mappings
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Extract key columns
        targets_col = receiving_cols.get('targets')
        receptions_col = receiving_cols.get('receptions')
        receiving_yards_col = receiving_cols.get('receiving_yards')
        receiving_tds_col = receiving_cols.get('receiving_touchdowns')
        
        # Catch rate (receptions / targets)
        if targets_col and receptions_col and both_cols_exist(df, [targets_col, receptions_col]):
            df['catch_rate'] = np.where(
                df[targets_col] > 0,
                df[receptions_col] / df[targets_col],
                0.0
            )
        else:
            df['catch_rate'] = 0.0
        
        # Yards per reception
        if receptions_col and receiving_yards_col and both_cols_exist(df, [receptions_col, receiving_yards_col]):
            df['yards_per_reception'] = np.where(
                df[receptions_col] > 0,
                df[receiving_yards_col] / df[receptions_col],
                0.0
            )
        else:
            df['yards_per_reception'] = 0.0
        
        # Yards per target
        if targets_col and receiving_yards_col and both_cols_exist(df, [targets_col, receiving_yards_col]):
            df['yards_per_target'] = np.where(
                df[targets_col] > 0,
                df[receiving_yards_col] / df[targets_col],
                0.0
            )
        else:
            df['yards_per_target'] = 0.0
        
        # Touchdowns per reception
        if receptions_col and receiving_tds_col and both_cols_exist(df, [receptions_col, receiving_tds_col]):
            df['touchdowns_per_reception'] = np.where(
                df[receptions_col] > 0,
                df[receiving_tds_col] / df[receptions_col],
                0.0
            )
        else:
            df['touchdowns_per_reception'] = 0.0
        
        # Touchdowns per target
        if targets_col and receiving_tds_col and both_cols_exist(df, [targets_col, receiving_tds_col]):
            df['touchdowns_per_target'] = np.where(
                df[targets_col] > 0,
                df[receiving_tds_col] / df[targets_col],
                0.0
            )
        else:
            df['touchdowns_per_target'] = 0.0
        
        # Target quality (combination of yards per target and TD rate)
        df['target_quality'] = (df['yards_per_target'] * 0.7) + (df['touchdowns_per_target'] * 30.0)
        
        return df
    
    def _calculate_per_game_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate WR per-game metrics using centralized utilities.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with WR per-game metrics added
        """
        df = df.copy()
        
        # Get games played column
        general_cols = self.column_mapper.get_column_mapping(df, ['general'])
        games_col = general_cols.get('games')
        if not games_col:
            self.logger.warning("No games column found for per-game calculations")
            # Set all per-game metrics to 0
            per_game_metrics = [
                'targets_per_game', 'receptions_per_game', 
                'receiving_yards_per_game', 'receiving_tds_per_game'
            ]
            for metric in per_game_metrics:
                df[metric] = 0.0
            return df
        
        # Get column mappings
        receiving_cols = self.column_mapper.get_column_mapping(df, ['receiving'])
        
        # Avoid division by zero
        games_played = df[games_col].replace(0, 1)
        
        # Receiving per-game stats
        receiving_stats = {
            'targets_per_game': receiving_cols.get('targets'),
            'receptions_per_game': receiving_cols.get('receptions'),
            'receiving_yards_per_game': receiving_cols.get('receiving_yards'),
            'receiving_tds_per_game': receiving_cols.get('receiving_touchdowns')
        }
        
        for stat_name, col_name in receiving_stats.items():
            if col_name and col_name in df.columns:
                df[stat_name] = df[col_name] / games_played
            else:
                df[stat_name] = 0.0
        
        return df
    
    def _calculate_usage_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate WR usage and opportunity metrics.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with WR usage metrics added
        """
        df = df.copy()
        
        # For now, set basic usage metrics to 0 or calculate from available data
        # In a full implementation, these would require team-level data
        
        # Target share (would need team passing attempts)
        df['target_share'] = 0.0
        
        # Air yards share (would need team air yards)
        df['air_yards_share'] = 0.0
        
        # Red zone opportunities (would need play-by-play data)
        df['red_zone_targets'] = 0.0
        df['red_zone_receptions'] = 0.0
        df['deep_targets'] = 0.0
        
        # Usage rates (would need more detailed data)
        df['slot_usage_rate'] = 0.0
        df['snap_share'] = 0.0
        
        return df
    
    def _calculate_advanced_metrics(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate advanced WR metrics and analytics.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with advanced WR metrics added
        """
        df = df.copy()
        
        # Advanced metrics that would require more detailed data
        # For now, set to 0 or estimate from available stats
        
        df['average_depth_of_target'] = 0.0
        df['yards_after_catch_per_reception'] = 0.0
        df['air_yards_per_target'] = 0.0
        df['contested_catch_rate'] = 0.0
        df['separation_at_catch'] = 0.0
        df['route_diversity_score'] = 0.0
        
        # Target distribution metrics
        df['high_value_target_rate'] = 0.0
        df['short_target_rate'] = 0.0
        df['medium_target_rate'] = 0.0
        df['deep_target_rate'] = 0.0
        df['intermediate_accuracy'] = 0.0
        df['deep_accuracy'] = 0.0
        
        return df
    
    def _calculate_role_classification(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate WR role classification scores based on usage patterns.
        
        Args:
            df: DataFrame containing WR player data
            
        Returns:
            DataFrame with role classification features added
        """
        df = df.copy()
        
        # Primary receiver score (based on target volume)
        df['primary_receiver_score'] = np.where(
            df['targets_per_game'] >= 8,
            df['targets_per_game'] / 12.0,  # Scale to 0-1
            0.0
        )
        
        # Slot receiver score (would be based on alignment data if available)
        df['slot_receiver_score'] = 0.0
        
        # Deep threat score (based on yards per target)
        df['deep_threat_score'] = np.where(
            df['yards_per_target'] >= 9,  # Lowered threshold to be more inclusive
            df['yards_per_target'] / 15.0,  # Scale to 0-1
            0.0
        )
        
        # Possession receiver score (based on catch rate and volume)
        df['possession_receiver_score'] = np.where(
            (df['catch_rate'] >= 0.65) & (df['targets_per_game'] >= 5),
            (df['catch_rate'] + (df['targets_per_game'] / 10.0)) / 2.0,
            0.0
        )
        
        # Red zone specialist score (would be based on red zone targets if available)
        df['red_zone_specialist_score'] = 0.0
        
        # Consistency metrics (would need game-by-game data)
        df['target_consistency_score'] = 0.0
        df['weekly_production_volatility'] = 0.0
        df['boom_game_rate'] = 0.0
        df['reliable_target_rate'] = 0.0
        
        # Versatility score (combination of different role scores)
        df['wr_versatility_score'] = (
            df['primary_receiver_score'] * 0.4 +
            df['deep_threat_score'] * 0.3 +
            df['possession_receiver_score'] * 0.3
        )
        
        return df


def both_cols_exist(df: pd.DataFrame, columns: List[str]) -> bool:
    """Helper function to check if all columns exist in DataFrame."""
    return all(col in df.columns for col in columns if col is not None)


# Legacy compatibility function
def engineer_wr_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Legacy compatibility function for WR feature engineering.
    
    This function maintains backward compatibility with existing code
    while using the new WRFeatureEngineer class internally.
    
    Args:
        df: DataFrame containing WR player data
        
    Returns:
        DataFrame with WR-specific features added
    """
    engineer = WRFeatureEngineer()
    return engineer.engineer_features(df)