"""
Abstract base class for feature engineering operations.

This module provides a consistent interface for all feature engineering classes,
eliminating code duplication and ensuring standardized behavior across positions.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Tuple, Union, Any
import pandas as pd
import numpy as np
import logging
from .logging_config import get_logger


class BaseFeatureEngineer(ABC):
    """
    Abstract base class for position-specific feature engineering.
    
    This class defines the standard interface that all feature engineering
    classes must implement, ensuring consistency and enabling polymorphic behavior.
    """
    
    def __init__(self, position: str, logger: Optional[logging.Logger] = None):
        """
        Initialize the feature engineer.
        
        Args:
            position: Player position (QB, RB, WR, TE, K, DST)
            logger: Optional logger instance
        """
        self.position = position.upper()
        self.logger = logger or get_logger(f"{self.__class__.__name__}_{self.position}")
        self._validate_position()
        
    def _validate_position(self) -> None:
        """Validate that the position is supported."""
        valid_positions = ['QB', 'RB', 'WR', 'TE', 'K', 'DST']
        if self.position not in valid_positions:
            raise ValueError(f"Invalid position: {self.position}. Must be one of {valid_positions}")
    
    @abstractmethod
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Engineer position-specific features from player data.
        
        Args:
            df: DataFrame containing player data for this position
            
        Returns:
            DataFrame with engineered features added
            
        Raises:
            ValueError: If input data is invalid
            DataProcessingError: If feature engineering fails
        """
        pass
    
    @abstractmethod
    def get_required_columns(self) -> List[str]:
        """
        Get list of columns required for feature engineering.
        
        Returns:
            List of column names that must be present in input data
        """
        pass
    
    @abstractmethod
    def get_generated_features(self) -> List[str]:
        """
        Get list of features that will be generated by this engineer.
        
        Returns:
            List of feature names that will be added to the DataFrame
        """
        pass
    
    def validate_input_data(self, df: pd.DataFrame) -> None:
        """
        Validate input data meets requirements for feature engineering.
        
        Args:
            df: DataFrame to validate
            
        Raises:
            ValueError: If data validation fails
        """
        if df.empty:
            raise ValueError("Input DataFrame is empty")
        
        # Check for required columns
        required_cols = self.get_required_columns()
        missing_cols = [col for col in required_cols if col not in df.columns]
        if missing_cols:
            raise ValueError(f"Missing required columns for {self.position}: {missing_cols}")
        
        # Check position filter
        if 'position' in df.columns:
            position_data = df[df['position'] == self.position]
            if position_data.empty:
                raise ValueError(f"No {self.position} players found in data")
        
        self.logger.info(f"Input validation passed for {len(df)} {self.position} players")
    
    def calculate_per_game_stats(self, df: pd.DataFrame, 
                                stats_columns: List[str],
                                games_column: str = 'games') -> pd.DataFrame:
        """
        Calculate per-game averages for specified statistics.
        
        Args:
            df: DataFrame containing player statistics
            stats_columns: List of column names to calculate per-game stats for
            games_column: Name of the games played column
            
        Returns:
            DataFrame with per-game statistics added
        """
        df_result = df.copy()
        
        if games_column not in df_result.columns:
            self.logger.warning(f"Games column '{games_column}' not found, skipping per-game calculations")
            return df_result
        
        # Replace 0 games with 1 to avoid division by zero
        games_played = df_result[games_column].replace(0, 1)
        
        for col in stats_columns:
            if col in df_result.columns:
                per_game_col = f"{col}_per_game"
                df_result[per_game_col] = df_result[col] / games_played
                self.logger.debug(f"Calculated {per_game_col} for {self.position}")
        
        return df_result
    
    def calculate_efficiency_metrics(self, df: pd.DataFrame,
                                   efficiency_rules: Dict[str, Dict[str, str]]) -> pd.DataFrame:
        """
        Calculate efficiency metrics based on provided rules.
        
        Args:
            df: DataFrame containing player statistics
            efficiency_rules: Dict mapping efficiency metric names to calculation rules
                             Format: {'metric_name': {'numerator': 'col1', 'denominator': 'col2'}}
            
        Returns:
            DataFrame with efficiency metrics added
        """
        df_result = df.copy()
        
        for metric_name, rule in efficiency_rules.items():
            numerator_col = rule.get('numerator')
            denominator_col = rule.get('denominator')
            
            if (numerator_col in df_result.columns and 
                denominator_col in df_result.columns):
                
                # Calculate efficiency, avoiding division by zero
                mask = df_result[denominator_col] > 0
                df_result[metric_name] = 0.0
                df_result.loc[mask, metric_name] = (
                    df_result.loc[mask, numerator_col] / 
                    df_result.loc[mask, denominator_col]
                )
                
                self.logger.debug(f"Calculated {metric_name} for {self.position}")
        
        return df_result
    
    def calculate_usage_metrics(self, df: pd.DataFrame,
                              team_totals: Dict[str, str]) -> pd.DataFrame:
        """
        Calculate usage share metrics against team totals.
        
        Args:
            df: DataFrame containing player statistics
            team_totals: Dict mapping player stats to team total columns
                        Format: {'player_stat': 'team_total_stat'}
            
        Returns:
            DataFrame with usage metrics added
        """
        df_result = df.copy()
        
        for player_stat, team_stat in team_totals.items():
            if (player_stat in df_result.columns and 
                team_stat in df_result.columns):
                
                usage_metric = f"{player_stat}_share"
                mask = df_result[team_stat] > 0
                df_result[usage_metric] = 0.0
                df_result.loc[mask, usage_metric] = (
                    df_result.loc[mask, player_stat] / 
                    df_result.loc[mask, team_stat]
                )
                
                self.logger.debug(f"Calculated {usage_metric} for {self.position}")
        
        return df_result
    
    def add_lag_features(self, df: pd.DataFrame,
                        feature_columns: List[str],
                        lag_periods: List[int] = [1]) -> pd.DataFrame:
        """
        Add lagged versions of specified features.
        
        Args:
            df: DataFrame containing features to lag
            feature_columns: List of columns to create lag features for
            lag_periods: List of lag periods (e.g., [1, 2] for L1 and L2)
            
        Returns:
            DataFrame with lag features added
        """
        df_result = df.copy()
        
        for col in feature_columns:
            if col in df_result.columns:
                for lag in lag_periods:
                    lag_col = f"{col}_L{lag}"
                    # For now, just create placeholder lag features
                    # In a real implementation, this would use historical data
                    df_result[lag_col] = df_result[col].fillna(0)
                    self.logger.debug(f"Added lag feature {lag_col} for {self.position}")
        
        return df_result
    
    def get_position(self) -> str:
        """Get the position this engineer handles."""
        return self.position
    
    def get_feature_categories(self) -> Dict[str, List[str]]:
        """
        Get features organized by category.
        
        Returns:
            Dictionary mapping category names to lists of feature names
        """
        all_features = self.get_generated_features()
        
        # Default categorization - subclasses can override
        categories = {
            'per_game': [f for f in all_features if '_per_game' in f],
            'efficiency': [f for f in all_features if any(x in f for x in ['_rate', '_percentage', '_per_'])],
            'usage': [f for f in all_features if '_share' in f],
            'lag': [f for f in all_features if '_L' in f],
            'other': [f for f in all_features if not any(cat in f for cat in ['_per_game', '_rate', '_percentage', '_share', '_L'])]
        }
        
        return {k: v for k, v in categories.items() if v}  # Remove empty categories
    
    def __repr__(self) -> str:
        """String representation of the feature engineer."""
        return f"{self.__class__.__name__}(position='{self.position}')"